# Generated by Django 2.1.5 on 2019-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.TextField()),
                ('titel', models.TextField()),
                ('timer', models.TextField()),
                ('ekstra_timer', models.TextField(blank=True, null=True)),
                ('ekstra_timer_beskrivelse', models.TextField(blank=True, null=True)),
                ('kørsel', models.TextField()),
                ('opgave_beskrivelse', models.TextField()),
                ('materialer', models.TextField()),
            ],
        ),
    ]
